namespace ACData
{
    public enum Table
    {
        None,
        Weenie,
        AnimPart,
        Attribute,
        Attribute2nd,
        BodyPart,
        Book,
        BookPageData,
        Bool,
        CreateList,
        DID,
        Emote,
        EmoteAction,
        EventFilter,
        Float,
        Generator,
        Int,
        Int64,
        IID,
        Palette,
        Position,
        Skill,
        SpellBook,
        String,
        TextureMap
    }
}
